- name: Open 5666 port for NRPE
  lineinfile: dest=/etc/network/if-pre-up.d/iptables line='/sbin/iptables -A INPUT -i vmbr0 -p tcp --dport 5666 -j ACCEPT'

- name: Open LIVE 5666 port for NRPE
  command: /sbin/iptables -A INPUT -i vmbr0 -p tcp --dport 5666 -j ACCEPT

- name: Allow ping from nagios
  lineinfile: dest=/etc/network/if-pre-up.d/iptables line='/sbin/iptables -A INPUT -p icmp -s 54.38.192.56 -j ACCEPT'

- name: Open LIVE ping from nagios
  command: /sbin/iptables -A INPUT -p icmp -s 54.38.192.56 -j ACCEPT

- name: Allow ssh from nagios
  lineinfile: dest=/etc/network/if-pre-up.d/iptables line='/sbin/iptables -A INPUT -i vmbr0 -p tcp --dport 22 -s 54.38.192.56 -j ACCEPT'

- name: Allow LIVE ssh from nagios
  command: /sbin/iptables -A INPUT -i vmbr0 -p tcp --dport 22 -s 54.38.192.56 -j ACCEPT