###### INSTALL NEED SOFT ######
- name: Install need soft
  apt: pkg={{ item }} state=latest
  with_items:
    - nagios-nrpe-server
    - nagios-plugins
    - autoconf 
    - gcc 
    - libc6 
    - make 
    - wget 
    - unzip 
    - libgd-dev
- name: Install Sys::Statistics::Linux
  shell: /usr/bin/perl -MCPAN -e 'install Sys::Statistics::Linux'

###### COPY CONFIG FILES ######
- name: Copy need files
  template: 
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  notify:
    - reload nagios-nrpe-server
  with_items:
    - { src: 'nrpe.cfg',  dest: '/etc/nagios/nrpe.cfg' }
    - { src: 'check_linux_stats.pl', dest: '/usr/lib/nagios/plugins/check_linux_stats.pl' } 
    - { src: 'check_mem',  dest: '/usr/lib/nagios/plugins/check_mem' }

###### Set permission "check_linux_stats.pl", "check_mem" ######
- name: Set permission 0777 "check_linux_stats.pl", "check_mem"
  file:
    path: '{{ item }}'
    mode: 0777
  with_items:
    - '/usr/lib/nagios/plugins/check_linux_stats.pl'
    - '/usr/lib/nagios/plugins/check_mem'

###### START NRPE-SERVER ######
- name: Starting nagios-nrpe-server
  service: name={{ item }} state=started
  with_items:
    - nagios-nrpe-server

###### ADD TO AUTORUN SERVICES ######
- name: Add to autorun nagios-nrpe-server
  service: name=nagios-nrpe-server enabled=yes